version: '3'
services:
  monitor:
    image: "nanotools/nanonodemonitor"
    restart: "unless-stopped"
    ports:
     - "8081:80"
    volumes:
     - "/mnt/volumes/nanonodemonitor:/opt"
  node:
    image: "nanocurrency/nano"
    restart: "unless-stopped"
    ports:
     - "7075:7075/udp"
     - "7075:7075"
     - "127.0.0.1:7077:7076"
    volumes:
     - "/mnt/volumes/nanonode:/root"